function N=InterpolT6(ksi,eta)
% Cette fonction évalue numériquement la valeur des fonctions N aux
% coordonnées demandées en Ksi et Eta:
lambda=1-ksi-eta;
N =[ -lambda*(1-2*lambda), ...        
     4*ksi*lambda,  ...                    
    -ksi*(1-2*ksi),    ...                                
    4*ksi*eta, ...
    -eta*(1-2*eta), ...
    4*lambda*eta];
end