function N=InterpolQ4(ksi,eta)
% Cette fonction évalue numériquement la valeur des fonctions N aux
% coordonnées demandées en Ksi et Eta:
N =[ (1-ksi-eta+ksi*eta)/4, ...        
    (1+ksi-eta-ksi*eta)/4,  ...                    
    (1+ksi+eta+ksi*eta)/4,    ...                                
    (1-ksi+eta-ksi*eta)/4];
 